---
title: "Daggity tests"
output: html_document
date: "2024-11-01"
---

```{r}
library("dagitty")
```


```{r}
dag<- dagitty(dag {
bb="-3.631,-3.459,3.544,3.639"
"Alcohol frequency" [adjusted,pos="-2.378,0.215"]
"Education level" [adjusted,pos="-3.296,1.312"]
"Excercice type" [adjusted,pos="-2.540,-0.713"]
"Excercise frequency" [adjusted,pos="-2.367,-0.311"]
"Health conciousness" [latent,pos="-3.215,-1.515"]
"Hours of sleep" [adjusted,pos="2.061,-3.186"]
"N diseases" [pos="2.493,2.284"]
"Recreational drug use" [adjusted,pos="1.050,-2.105"]
"Smoking frequency" [adjusted,pos="-2.419,0.750"]
"Stem cells" [adjusted,pos="0.092,-1.869"]
"TA 65" [adjusted,pos="-1.247,-1.741"]
"WBC composition" [pos="3.140,1.133"]
APOE [adjusted,pos="1.304,1.811"]
Age [adjusted,pos="-2.655,-3.361"]
AgeDev [outcome,pos="2.592,-0.460"]
DHEA [adjusted,pos="1.368,-2.178"]
Diet [latent,pos="-2.528,1.561"]
Ethnicity [pos="2.049,1.802"]
Exosomes [adjusted,pos="1.962,-2.468"]
Fasting [latent,pos="-2.563,2.025"]
Fish.oil [adjusted,pos="-1.922,-1.732"]
Glucose [adjusted,pos="0.023,1.695"]
HRT [adjusted,pos="-0.272,-1.823"]
Hba1c [pos="-0.664,2.400"]
MTHFR [pos="1.662,1.802"]
Metformin [adjusted,pos="-1.576,-1.741"]
NAD [adjusted,pos="-0.906,-1.750"]
NR [adjusted,pos="-0.595,-1.787"]
Rapamycin [exposure,pos="-2.604,-1.604"]
Resveratrol [adjusted,pos="-2.263,-1.738"]
Senolytics [adjusted,pos="1.680,-2.268"]
Sex [adjusted,pos="1.437,0.964"]
Stress [adjusted,pos="2.949,-3.254"]
Sulphoraphane [adjusted,pos="0.704,-1.996"]
T2D [adjusted,pos="-2.927,-0.971"]
Triglycerides [adjusted,pos="0.138,1.000"]
Vitamins [adjusted,pos="0.404,-1.914"]
"Alcohol frequency" -> AgeDev
"Education level" -> "Health conciousness"
"Education level" -> "Smoking frequency"
"Education level" -> Diet
"Education level" -> T2D
"Excercice type" -> AgeDev
"Excercise frequency" -> AgeDev
"Health conciousness" -> "Alcohol frequency" [pos="-3.088,-0.302"]
"Health conciousness" -> "Excercice type" [pos="-2.896,-1.106"]
"Health conciousness" -> "Excercise frequency" [pos="-2.933,-0.178"]
"Health conciousness" -> "Hours of sleep" [pos="-2.580,-3.468"]
"Health conciousness" -> "Recreational drug use" [pos="-2.199,-3.259"]
"Health conciousness" -> "Smoking frequency" [pos="-2.915,0.928"]
"Health conciousness" -> "Stem cells" [pos="-2.113,-2.896"]
"Health conciousness" -> "TA 65" [pos="-2.038,-2.459"]
"Health conciousness" -> DHEA [pos="-2.321,-3.459"]
"Health conciousness" -> Diet [pos="-3.210,0.384"]
"Health conciousness" -> Exosomes [pos="-2.673,-3.459"]
"Health conciousness" -> Fasting [pos="-3.348,1.160"]
"Health conciousness" -> Fish.oil [pos="-2.384,-2.077"]
"Health conciousness" -> HRT [pos="-2.067,-2.814"]
"Health conciousness" -> Metformin [pos="-2.246,-2.246"]
"Health conciousness" -> NAD [pos="-2.130,-2.532"]
"Health conciousness" -> NR [pos="-1.986,-2.696"]
"Health conciousness" -> Rapamycin
"Health conciousness" -> Resveratrol [pos="-2.604,-1.899"]
"Health conciousness" -> Senolytics [pos="-2.390,-3.468"]
"Health conciousness" -> Sulphoraphane [pos="-2.194,-3.132"]
"Health conciousness" -> Vitamins [pos="-2.044,-3.050"]
"Hours of sleep" -> "WBC composition" [pos="3.290,-1.460"]
"N diseases" -> AgeDev
"Recreational drug use" -> AgeDev
"Smoking frequency" -> AgeDev
"Stem cells" -> AgeDev
"TA 65" -> AgeDev
"WBC composition" -> AgeDev
APOE -> AgeDev
APOE -> Triglycerides
Age -> "Health conciousness"
Age -> "WBC composition" [pos="-3.469,-0.820"]
Age -> AgeDev [pos="2.667,-3.450"]
DHEA -> AgeDev
Diet -> AgeDev
Diet -> Glucose
Diet -> Hba1c
Diet -> T2D [pos="-2.973,0.411"]
Diet -> Triglycerides
Ethnicity -> "N diseases"
Ethnicity -> "WBC composition"
Ethnicity -> AgeDev
Exosomes -> AgeDev
Fasting -> AgeDev
Fasting -> Glucose
Fasting -> Hba1c
Fasting -> Triglycerides
Fish.oil -> AgeDev
Glucose -> AgeDev
HRT -> AgeDev
MTHFR -> AgeDev
Metformin -> AgeDev
Metformin -> Glucose
Metformin -> Hba1c
NAD -> AgeDev
NR -> AgeDev
Rapamycin -> AgeDev
Resveratrol -> AgeDev
Senolytics -> AgeDev
Sex -> "Excercice type"
Sex -> AgeDev
Stress -> "Hours of sleep"
Stress -> "WBC composition" [pos="3.429,0.122"]
Stress -> AgeDev
Sulphoraphane -> AgeDev
T2D -> Glucose [pos="-1.080,-1.060"]
T2D -> Hba1c [pos="-1.813,-1.105"]
T2D -> Metformin
Triglycerides -> AgeDev
Vitamins -> AgeDev
})

```

