---
title: "Imputation"
output: html_document
date: "2024-10-25"
---


#Import functions
```{r}

library(pacman)
p_load(dplyr)


# source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/set_NA_percent_and_imp_cols().R")
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/mixed_correlation_matrix().R")
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/imputationFunctions.R")
```

# Data exploration can be removed later
```{r}
# #Load data
# load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# # Rename dataframe in this new script
# data<-data_with_ageDev
# rm(data_with_ageDev) # Remove old dataframe

# print(colnames(data))

```



### Calculate corr matrix
```{r}
  # Remove unnecessary columns
  # data4_without_cols <- subset(data4, select = -c(Hannum.PC, Horvath.PC, Telomere.Values.PC, GrimAge.PC, PhenoAge.PC,
  #                                        SystemsAge.Heart, SystemsAge.Hormone, SystemsAge.Blood, SystemsAge.Brain, 
  #                                        SystemsAge.Inflammation, SystemsAge.Immune, SystemsAge.Kidney, SystemsAge.Liver,
  #                                        SystemsAge.Metabolic, SystemsAge.Lung, SystemsAge.MusculoSkeletal, SystemsAge,
  #                                        OMICmAge, fasting, Main.Diet, NAD, TA65, sulforaphane, DHEA_new, Rapamycin_new,
  #                                        SASP_supressors, Metformin_new, Resveratrol_new, Exosomes, stem_cells, HRT, 
  #                                        spermidine, semaglutide, vitaminD, AKG, Hannum.PCAgeDev, Horvath.PCAgeDev, 
  #                                         GrimAge.PCAgeDev, PhenoAge.PCAgeDev, OMICmAgeAgeDev,
  #                                        SystemsAge.BloodAgeDev, SystemsAge.BrainAgeDev, SystemsAge.InflammationAgeDev,
  #                                        SystemsAge.HeartAgeDev, SystemsAge.HormoneAgeDev, SystemsAge.ImmuneAgeDev,
  #                                        SystemsAge.KidneyAgeDev, SystemsAge.LiverAgeDev, SystemsAge.MetabolicAgeDev,
  #                                        SystemsAge.LungAgeDev, SystemsAge.MusculoSkeletalAgeDev, SystemsAgeAgeDev, DunedinPACE))

# OMICage och grimage är ej korrolerade över 0,8
# 
# Kolla OMICage-dunedin och dunedin-grimAge

# corr_df<-mixed_correlation_matrix(data4, cols_to_skip = c("Patient.ID", "PID", "Collection.Date", "Array", "survey_version"))

```

# Do imputation for diabetics - not done
```{r}
#Load data
load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# Rename dataframe in this new script
data<-data_with_ageDev
rm(data_with_ageDev) # Remove old dataframe

data <- data %>% filter(Diabetes2 == 1)

# Separate columns to keep unimputed
cols_to_exclude <- c("Alcohol.per.week", "Level.of.Education", "Hours.of.sleep.per.night",
  "Tobacco.Use", "Exercise.per.week", "Drug.Alcohol.mother", "Drug.Alcohol.father", "Mother.Nicotine.Use", "Mother.Pregnancy.Complications", "Caffeine.Use", "Marital.Status", "Sexual.Frequency")


impute_survey_data(data_to_drop_cols_from=data, surveyVersion = 1, missing_threshold = 50, 
                                 amount_of_mice_datasets_to_impute = 2, max_iterations_per_dataset = 1, 
                                 cols_to_exclude_from_imputation_entirely = cols_to_exclude, savePath = "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1_only_females")


```


# Do imputation for prediabetics 
```{r}
#Load data
load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# Rename dataframe in this new script
data<-data_with_ageDev
rm(data_with_ageDev) # Remove old dataframe

data <- data %>% filter(Prediabetes == 1)
# Separate columns to keep unimputed
cols_to_exclude <- c("Alcohol.per.week", "Level.of.Education", "Hours.of.sleep.per.night",
  "Tobacco.Use", "Exercise.per.week", "Drug.Alcohol.mother", "Drug.Alcohol.father", "Mother.Nicotine.Use", "Mother.Pregnancy.Complications", "Caffeine.Use", "Marital.Status", "Sexual.Frequency")


impute_survey_data(data_to_drop_cols_from=data, surveyVersion = 1, missing_threshold = 50, 
                                 amount_of_mice_datasets_to_impute = 2, max_iterations_per_dataset = 1, 
                                 cols_to_exclude_from_imputation_entirely = cols_to_exclude, savePath = "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1_only_females")


```


# Do imputation for non-diabetics non prediabetics 
```{r}
#Load data
load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# Rename dataframe in this new script
data<-data_with_ageDev
rm(data_with_ageDev) # Remove old dataframe

data <- data %>% filter(Prediabetes == 0 & Diabetes2 == 0)
# Separate columns to keep unimputed
cols_to_exclude <- c("Alcohol.per.week", "Level.of.Education", "Hours.of.sleep.per.night",
  "Tobacco.Use", "Exercise.per.week", "Drug.Alcohol.mother", "Drug.Alcohol.father", "Mother.Nicotine.Use", "Mother.Pregnancy.Complications", "Caffeine.Use", "Marital.Status", "Sexual.Frequency")


impute_survey_data(data_to_drop_cols_from=data, surveyVersion = 1, missing_threshold = 50, 
                                 amount_of_mice_datasets_to_impute = 2, max_iterations_per_dataset = 1, 
                                 cols_to_exclude_from_imputation_entirely = cols_to_exclude, savePath = "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1_only_females")


```

# Do age-wise imputation
```{r}
#Load data
load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# Rename dataframe in this new script
data<-data_with_ageDev
rm(data_with_ageDev) # Remove old dataframe

# Calculate the median age
median_age <- median(data$Decimal.Chronological.Age, na.rm = TRUE)
print(paste("median:", median_age))

# Split the data into two data frames
data_lower <- data[data$Decimal.Chronological.Age < median_age, ]
data_upper <- data[data$Decimal.Chronological.Age >= median_age, ]

# Separate columns to keep unimputed
cols_to_exclude <- c("Alcohol.per.week", "Level.of.Education", "Hours.of.sleep.per.night",
  "Tobacco.Use", "Exercise.per.week", "Drug.Alcohol.mother", "Drug.Alcohol.father", "Mother.Nicotine.Use", "Mother.Pregnancy.Complications", "Caffeine.Use", "Marital.Status", "Sexual.Frequency")

#Run imputation for older group
impute_survey_data(data_to_drop_cols_from=data_upper, surveyVersion = 1, missing_threshold = 50, 
                                 amount_of_mice_datasets_to_impute = 2, max_iterations_per_dataset = 1, 
                                 cols_to_exclude_from_imputation_entirely = cols_to_exclude, savePath = "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1_older")

#Run imputation for younger group
impute_survey_data(data_to_drop_cols_from=data_lower, surveyVersion = 1, missing_threshold = 50, 
                                 amount_of_mice_datasets_to_impute = 2, max_iterations_per_dataset = 1, 
                                 cols_to_exclude_from_imputation_entirely = cols_to_exclude, savePath = "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1_younger")

```

### Impute survey 1 - All participants
```{r}
#Load data
load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# Rename dataframe in this new script
data<-data_with_ageDev
rm(data_with_ageDev) # Remove old dataframe

# Separate columns to keep unimputed
cols_to_exclude <- c("Alcohol.per.week", "Level.of.Education", "Hours.of.sleep.per.night",
  "Tobacco.Use", "Exercise.per.week", "Drug.Alcohol.mother", "Drug.Alcohol.father", "Mother.Nicotine.Use", "Mother.Pregnancy.Complications", "Caffeine.Use", "Marital.Status", "Sexual.Frequency")

impute_survey_data(data_to_drop_cols_from=data, surveyVersion = 1, missing_threshold = 50, 
                                 amount_of_mice_datasets_to_impute = 2, max_iterations_per_dataset = 1, 
                                 cols_to_exclude_from_imputation_entirely = cols_to_exclude, savePath = "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1")

```


### Impute survey 1 - only females
```{r}
#Load data
load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# Rename dataframe in this new script
data<-data_with_ageDev
rm(data_with_ageDev) # Remove old dataframe

# Remove males from data
data <- data %>% filter(Biological.Sex == "Female")
# Separate columns to keep unimputed
cols_to_exclude <- c("Alcohol.per.week", "Level.of.Education", "Hours.of.sleep.per.night",
  "Tobacco.Use", "Exercise.per.week", "Drug.Alcohol.mother", "Drug.Alcohol.father", "Mother.Nicotine.Use", "Mother.Pregnancy.Complications", "Caffeine.Use", "Marital.Status", "Sexual.Frequency")


impute_survey_data(data_to_drop_cols_from=data, surveyVersion = 1, missing_threshold = 50, 
                                 amount_of_mice_datasets_to_impute = 2, max_iterations_per_dataset = 1, 
                                 cols_to_exclude_from_imputation_entirely = cols_to_exclude, savePath = "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1_only_females")


```

### Impute survey 1 - only males
```{r}

#Load data
load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# Rename dataframe in this new script
data<-data_with_ageDev
rm(data_with_ageDev) # Remove old dataframe

# Remove females from data
data <- data %>% filter(Biological.Sex == "Male")

# Separate columns to keep unimputed
cols_to_exclude <- c("Alcohol.per.week", "Level.of.Education", "Hours.of.sleep.per.night",
  "Tobacco.Use", "Exercise.per.week", "Drug.Alcohol.mother", "Drug.Alcohol.father", "Mother.Nicotine.Use", "Mother.Pregnancy.Complications", "Caffeine.Use", "Marital.Status", "Sexual.Frequency")

impute_survey_data(data_to_drop_cols_from=data, surveyVersion = 1, missing_threshold = 50, 
                                 amount_of_mice_datasets_to_impute = 2, max_iterations_per_dataset = 1, 
                                 cols_to_exclude_from_imputation_entirely = cols_to_exclude, savePath = "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1_only_males")


```



### Impute survey 2
```{r}
# # Adjust this according to each survey
# surveyVersion=2
# missing_threshold=50
# max_iterations_per_dataset = 5
# #------------------------------------
# #Load data
# load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# # Rename dataframe in this new script
# data_to_drop_cols_from<-data_with_ageDev
# rm(data_with_ageDev) # Remove old dataframe

# data_to_drop_cols_from <- subset(data_to_drop_cols_from, survey_version == surveyVersion) ##Important row!!



# # Save a plot of how the data looks before cols with more missing data than the threshold is dropped
#   save_missing_data_plot(
#     data =  data_to_drop_cols_from,
#     survey_version_filter = surveyVersion,
#     output_dir= "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output", # Replace with your desired directory,
#     filename_prefix = "missing_data_before_removal_of_cols_for_survey_version_"
#   )
  
# #Prepare data for imputation by removing columns with more missing data than threshold
# df_to_impute<-set_NA_percent_and_imp_cols(data = data_to_drop_cols_from, survey_version_filter = surveyVersion, missing_threshold = missing_threshold)

# # Save a plot of how the data looks before imputation
#   save_missing_data_plot(
#     data = df_to_impute,
#     survey_version_filter = surveyVersion,
#     output_dir= "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output", # Replace with your desired directory,
#     filename_prefix = "missing_data_after_removal_of_cols_for_survey_version_"
#   )
  
#   #Set amount_of_mice_datasets_to_impute
#   avg_missing_data <-average_missing(df_to_impute) #These days there is a rule of thumb to use whatever the average percentage rate of missingness is
#   amount_of_mice_datasets_to_impute=avg_missing_data
#   print(paste0("Amount of mice datasets to impute: ", amount_of_mice_datasets_to_impute))
  
# # Perform imputation
# imputed_data<-impute_survey(data=df_to_impute, survey_version_filter =surveyVersion, missing_data_threshold =missing_threshold, imputation_seed=12345, number_of_mice_datasets_to_impute=amount_of_mice_datasets_to_impute, max_iterations=max_iterations_per_dataset, cols_to_exclude_from_predictors = c("Patient.ID", "PID", "Collection.Date", "Array", "survey_version", "GrimAge.PC", "OMICmAge", "Hannum.PCAgeDev", "Horvath.PCAgeDev",
#                                                       "PhenoAge.PCAgeDev", "SystemsAge.BloodAgeDev",
#                                                       "SystemsAge.BrainAgeDev", "SystemsAge.InflammationAgeDev",
#                                                       "SystemsAge.HeartAgeDev", "SystemsAge.HormoneAgeDev",
#                                                       "SystemsAge.ImmuneAgeDev", "SystemsAge.KidneyAgeDev",
#                                                       "SystemsAge.LiverAgeDev", "SystemsAge.MetabolicAgeDev",
#                                                       "SystemsAge.LungAgeDev", "SystemsAge.MusculoSkeletalAgeDev",
#                                                       "SystemsAgeAgeDev", "Hannum.PC", "Horvath.PC",
#   "Telomere.Values.PC", "PhenoAge.PC", "SystemsAge.Blood",
#   "SystemsAge.Brain", "SystemsAge.Inflammation", "SystemsAge.Heart",
#   "SystemsAge.Hormone", "SystemsAge.Immune", "SystemsAge.Kidney",
#   "SystemsAge.Liver", "SystemsAge.Metabolic", "SystemsAge.Lung",
#   "SystemsAge.MusculoSkeletal", "SystemsAge"))

# # Save a plot of how the data looks after imputation
#   save_missing_data_plot(
#     data = complete(imputed_data, 1),
#     survey_version_filter = surveyVersion,
#     output_dir= "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output", # Replace with your desired directory,
#     filename_prefix = "missing_data_after_imputation_for_survey_version_"
#   )

# # Save the imputed datasets to a file
# save(imputed_data, file = paste0("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey",surveyVersion,".RData"))

# # # inspect results
# # densityplot(imputed_data)
# # stripplot(imputed_data)


```

### Impute survey 3
```{r}
# # Adjust this according to each survey
# surveyVersion=3
# missing_threshold=50
# # amount_of_mice_datasets_to_impute=5
# max_iterations_per_dataset = 5
# #------------------------------------
# #Load data
# load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")
# # Rename dataframe in this new script
# data_to_drop_cols_from<-data_with_ageDev
# rm(data_with_ageDev) # Remove old dataframe


# data_to_drop_cols_from <- subset(data_to_drop_cols_from, survey_version == surveyVersion) ##Important row!!
# # Check which rows where removed for testing
# data_to_drop_cols_from <- data_to_drop_cols_from %>%
#   relocate(Exercise.per.week, .after = last_col())
#   # Check which rows where removed for testing
# data_to_drop_cols_from <- data_to_drop_cols_from %>%
#   relocate(Exercise.Type, .after = last_col())

# # Save a plot of how the data looks before cols with more missing data than the threshold is dropped
#   save_missing_data_plot(
#     data =  data_to_drop_cols_from,
#     survey_version_filter = surveyVersion,
#     output_dir= "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output", # Replace with your desired directory,
#     filename_prefix = "missing_data_before_removal_of_cols_for_survey_version_"
#   )
  
# #Prepare data for imputation by removing columns with more missing data than threshold
# df_to_impute<-set_NA_percent_and_imp_cols(data = data_to_drop_cols_from, survey_version_filter = surveyVersion, missing_threshold = missing_threshold)

# # Save a plot of how the data looks before imputation
#   save_missing_data_plot(
#     data = df_to_impute,
#     survey_version_filter = surveyVersion,
#     output_dir= "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output", # Replace with your desired directory,
#     filename_prefix = "missing_data_after_removal_of_cols_for_survey_version_"
#   )
  
#   #Set amount_of_mice_datasets_to_impute
#   avg_missing_data <-average_missing(df_to_impute) #These days there is a rule of thumb to use whatever the average percentage rate of missingness is
#   amount_of_mice_datasets_to_impute=avg_missing_data
#   print(paste0("Amount of mice datasets to impute: ", amount_of_mice_datasets_to_impute))
  
  
# # Perform imputation
# imputed_data<-impute_survey(data=df_to_impute, survey_version_filter =surveyVersion, missing_data_threshold =missing_threshold, imputation_seed=12345, number_of_mice_datasets_to_impute=amount_of_mice_datasets_to_impute, max_iterations=max_iterations_per_dataset, cols_to_exclude_from_predictors = c("Patient.ID", "PID", "Collection.Date", "Array", "survey_version", "GrimAge.PC", "OMICmAge", "Hannum.PCAgeDev", "Horvath.PCAgeDev",
#                                                       "PhenoAge.PCAgeDev", "SystemsAge.BloodAgeDev",
#                                                       "SystemsAge.BrainAgeDev", "SystemsAge.InflammationAgeDev",
#                                                       "SystemsAge.HeartAgeDev", "SystemsAge.HormoneAgeDev",
#                                                       "SystemsAge.ImmuneAgeDev", "SystemsAge.KidneyAgeDev",
#                                                       "SystemsAge.LiverAgeDev", "SystemsAge.MetabolicAgeDev",
#                                                       "SystemsAge.LungAgeDev", "SystemsAge.MusculoSkeletalAgeDev",
#                                                       "SystemsAgeAgeDev", "Hannum.PC", "Horvath.PC",
#   "Telomere.Values.PC", "PhenoAge.PC", "SystemsAge.Blood",
#   "SystemsAge.Brain", "SystemsAge.Inflammation", "SystemsAge.Heart",
#   "SystemsAge.Hormone", "SystemsAge.Immune", "SystemsAge.Kidney",
#   "SystemsAge.Liver", "SystemsAge.Metabolic", "SystemsAge.Lung",
#   "SystemsAge.MusculoSkeletal", "SystemsAge"))

# # Save a plot of how the data looks after imputation
#   save_missing_data_plot(
#     data = complete(imputed_data, 1),
#     survey_version_filter = surveyVersion,
#     output_dir= "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output", # Replace with your desired directory,
#     filename_prefix = "missing_data_after_imputation_for_survey_version_"
#   )

# # Save the imputed datasets to a file
# save(imputed_data, file = paste0("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey",surveyVersion,".RData"))

# # # inspect results
# # densityplot(imputed_data)
# # stripplot(imputed_data)


```



