---
title: "Model 1"
output: html_document
date: "2024-11-01"
---
```{r}
# #Set working directory
# setwd("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program")

#import functions
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/modelingFunctions.R")
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/plot_forest().R")


```

```{r}
library(mice)
load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1.RData")
#rename object
imp_data_surv1 <- imputed_data
df1_imp_data_surv1<-complete(imputed_data, 1)

load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey2.RData")
#rename object
imp_data_surv2 <- imputed_data
df1_imp_data_surv1<-complete(imputed_data, 1)

load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey3.RData")
#rename object
imp_data_surv3 <- imputed_data
df1_imp_data_surv1<-complete(imputed_data, 1)
```

### Model 1 - Survey1
```{r}
interventions<-c("Rapamycin_new", "Metformin_new", "fasting", "NAD", "TA65", "sulforaphane", "DHEA_new", "SASP_supressors", "Resveratrol_new", "Exosomes", "HRT", "spermidine", "semaglutide", "vitaminD", "AKG")

lifestyle_covariates_survey1<-c("Marital.Status", "Level.of.Education", "Stress.Level", "Caffeine.Use", "Tobacco.Use", "Main.Diet", "Exercise.per.week", "Exercise.Type", "Sexual.Frequency", "Hours.of.sleep.per.night", "Lab.Fasting", "Main.Diet.Factor" , "BMI")

covariates_to_always_include<-c("Decimal.Chronological.Age", "Biological.Sex" )


combined_results_df<-model_exposure_wise(path="C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1.RData", outcome_vars=c("DunedinPACE", "GrimAge.PCAgeDev", "OMICmAgeAgeDev"), exposure_vars=c(interventions,lifestyle_covariates_survey1), covariate_vars = covariates_to_always_include)

plot_forest(combined_results_df[["DunedinPACE"]])
plot_forest(combined_results_df[["GrimAge.PCAgeDev"]])
plot_forest(combined_results_df[["OMICmAgeAgeDev"]])

DunedinPACE<-combined_results_df[["DunedinPACE"]]
GrimAge.PCAgeDev<-combined_results_df[["GrimAge.PCAgeDev"]]
OMICmAgeAgeDev<-combined_results_df[["OMICmAgeAgeDev"]]



lifestyle_covariates_survey1<-c("Marital.Status", "Level.of.Education", "Stress.Level", "Caffeine.Use", "Tobacco.Use", "Main.Diet", "Exercise.per.week", "Exercise.Type", "Sexual.Frequency", "Hours.of.sleep.per.night", "Main.Diet.Factor" , "BMI")

```



### Model 2 -survey 1
```{r}
covariates_to_always_include<-c(c("Decimal.Chronological.Age", "Biological.Sex",lifestyle_covariates_survey1 ))

combined_results_df<-model_exposure_wise(path="C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey1.RData", outcome_vars=c("DunedinPACE", "GrimAge.PCAgeDev", "OMICmAgeAgeDev"), exposure_vars=interventions, covariate_vars = covariates_to_always_include)

plot_forest(combined_results_df[["DunedinPACE"]])
plot_forest(combined_results_df[["GrimAge.PCAgeDev"]])
plot_forest(combined_results_df[["OMICmAgeAgeDev"]])

DunedinPACE<-combined_results_df[["DunedinPACE"]]
GrimAge.PCAgeDev<-combined_results_df[["GrimAge.PCAgeDev"]]
OMICmAgeAgeDev<-combined_results_df[["OMICmAgeAgeDev"]]


```

### Model 3 - Survey 1
```{r}

model3_DunedinPACE<-fit_imputed_lm(imp_data_surv1, outcome = "DunedinPACE", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_DunedinPACE)

model3_GrimAge.PCAgeDev<-fit_imputed_lm(imp_data_surv1, outcome = "GrimAge.PCAgeDev", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_GrimAge.PCAgeDev)

model3_OMICmAgeAgeDev<-fit_imputed_lm(imp_data_surv1, outcome = "OMICmAgeAgeDev", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_OMICmAgeAgeDev)
```


### model 1 - Survey2
```{r}
interventions<-c("Rapamycin_new", "Metformin_new", "fasting", "NAD", "TA65", "sulforaphane", "DHEA_new", "SASP_supressors", "Resveratrol_new", "Exosomes", "HRT", "spermidine", "semaglutide", "vitaminD", "AKG")

lifestyle_covariates_survey2<-c("Level.of.Education", "Stress.Level", "Tobacco.Use", "Hours.Sedentary.Remaining.Awake", "Strictly.Followed.Main.Diet", "Red.Meat.times.per.week", "Processed.Food.times.per.week", "Feel.Well.Rested.days.per.week", "Screens.before.bed", "Lab.Fasting")

covariates_to_always_include<-c("Decimal.Chronological.Age", "Biological.Sex" )


combined_results_df<-model_exposure_wise(path="C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey2.RData", outcome_vars=c("DunedinPACE", "GrimAge.PCAgeDev", "OMICmAgeAgeDev"), exposure_vars=c(interventions,lifestyle_covariates_survey2), covariate_vars = covariates_to_always_include)

plot_forest(combined_results_df[["DunedinPACE"]])
plot_forest(combined_results_df[["GrimAge.PCAgeDev"]])
plot_forest(combined_results_df[["OMICmAgeAgeDev"]])

DunedinPACE<-combined_results_df[["DunedinPACE"]]
GrimAge.PCAgeDev<-combined_results_df[["GrimAge.PCAgeDev"]]
OMICmAgeAgeDev<-combined_results_df[["OMICmAgeAgeDev"]]

```



### Model 2 -survey 2
```{r}
covariates_to_always_include<-c(c("Decimal.Chronological.Age", "Biological.Sex",lifestyle_covariates_survey2 ))

combined_results_df<-model_exposure_wise(path="C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey2.RData", outcome_vars=c("DunedinPACE", "GrimAge.PCAgeDev", "OMICmAgeAgeDev"), exposure_vars=interventions, covariate_vars = covariates_to_always_include)

plot_forest(combined_results_df[["DunedinPACE"]])
plot_forest(combined_results_df[["GrimAge.PCAgeDev"]])
plot_forest(combined_results_df[["OMICmAgeAgeDev"]])

DunedinPACE<-combined_results_df[["DunedinPACE"]]
GrimAge.PCAgeDev<-combined_results_df[["GrimAge.PCAgeDev"]]
OMICmAgeAgeDev<-combined_results_df[["OMICmAgeAgeDev"]]


```

### Model 3 -survey 2

```{r}

model3_DunedinPACE<-fit_imputed_lm(imp_data_surv2, outcome = "DunedinPACE", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_DunedinPACE)

model3_GrimAge.PCAgeDev<-fit_imputed_lm(imp_data_surv2, outcome = "GrimAge.PCAgeDev", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_GrimAge.PCAgeDev)

model3_OMICmAgeAgeDev<-fit_imputed_lm(imp_data_surv2, outcome = "OMICmAgeAgeDev", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_OMICmAgeAgeDev)
```

### model 1 - Survey3
```{r}
interventions<-c("Rapamycin_new", "Metformin_new", "fasting", "NAD", "TA65", "sulforaphane", "DHEA_new", "SASP_supressors", "Resveratrol_new", "Exosomes", "HRT", "spermidine", "semaglutide", "vitaminD", "AKG")

lifestyle_covariates_survey3<-c("Level.of.Education", "Stress.Level", "Tobacco.Use", "Hours.of.sleep.per.night", "Hours.Sedentary.Remaining.Awake", "Strictly.Followed.Main.Diet", "Red.Meat.times.per.week", "Processed.Food.times.per.week", "Feel.Well.Rested.days.per.week", "Screens.before.bed", "Lab.Fasting", "BMI")

covariates_to_always_include<-c("Decimal.Chronological.Age", "Biological.Sex" )

combined_results_df<-model_exposure_wise(path="C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey3.RData", outcome_vars=c("DunedinPACE", "GrimAge.PCAgeDev", "OMICmAgeAgeDev"), exposure_vars=c(interventions,lifestyle_covariates_survey3), covariate_vars = covariates_to_always_include)

plot_forest(combined_results_df[["DunedinPACE"]])
plot_forest(combined_results_df[["GrimAge.PCAgeDev"]])
plot_forest(combined_results_df[["OMICmAgeAgeDev"]])

DunedinPACE<-combined_results_df[["DunedinPACE"]]
GrimAge.PCAgeDev<-combined_results_df[["GrimAge.PCAgeDev"]]
OMICmAgeAgeDev<-combined_results_df[["OMICmAgeAgeDev"]]

```

### Model 2 -survey 3
```{r}

covariates_to_always_include<-c(c("Decimal.Chronological.Age", "Biological.Sex",lifestyle_covariates_survey3 ))

combined_results_df<-model_exposure_wise(path="C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/imputed_survey3.RData", outcome_vars=c("DunedinPACE", "GrimAge.PCAgeDev", "OMICmAgeAgeDev"), exposure_vars=interventions, covariate_vars = covariates_to_always_include)

plot_forest(combined_results_df[["DunedinPACE"]])
plot_forest(combined_results_df[["GrimAge.PCAgeDev"]])
plot_forest(combined_results_df[["OMICmAgeAgeDev"]])

DunedinPACE<-combined_results_df[["DunedinPACE"]]
GrimAge.PCAgeDev<-combined_results_df[["GrimAge.PCAgeDev"]]
OMICmAgeAgeDev<-combined_results_df[["OMICmAgeAgeDev"]]


```

### Model 3 -survey 3
```{r}

model3_DunedinPACE<-fit_imputed_lm(imp_data_surv3, outcome = "DunedinPACE", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_DunedinPACE)

model3_GrimAge.PCAgeDev<-fit_imputed_lm(imp_data_surv3, outcome = "GrimAge.PCAgeDev", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_GrimAge.PCAgeDev)

model3_OMICmAgeAgeDev<-fit_imputed_lm(imp_data_surv3, outcome = "OMICmAgeAgeDev", exposures=interventions, covariates=covariates_to_always_include)
plot_forest(model3_OMICmAgeAgeDev)
```

