---
title: "Table 1"
output: html_document
date: "2024-08-09"
---


## Import Data
```{r}
library(dplyr)

load("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/data_after_step4")


survey1 <- filter(data_with_ageDev, survey_version == 1)


```


## Import functions to handle data
```{r}
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/format_pvalue().R")
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/make_table_row_N_indivudals().R")
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/make_table_row_discrete().R")
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/make_table_row_continuous().R")
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/fill_table_with_categorical().R")
source("C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Program/remove_other().R")


```

## Seperate individuals using survey1 (done in master harmonizer now)
```{r}
# collumns_to_use <- c("Decimal.Chronological.Age", "BMI", "Stress.Level", "Biological.Sex", "Alcohol.per.week", "Level.of.Education", "Tobacco.Use", "Exercise.per.week", "Exercise.Type", "Hours.of.sleep.per.night", "Ethnicity", "Cancer.Diagnosis.any", "Cardiovascular.any", "Respiratory.Disease.any", "Endocrine.Disease.any", "Skin.Hair.any", "Gastrointestinal.any", "Genito.Urinary.any", "Musculoskeletal.any", "Neuropsychological.any", "Reproductive.any", "Immune.any", "Diabetes1", "Diabetes2", "Prediabetes", "NAD", "TA65", "sulforaphane", "DHEA_new", "Rapamycin_new", "SASP_supressors", "Resveratrol_new", "Exosomes", "stem_cells", "HRT", "vitaminD", "Main.Diet")
# 
# #Remove rows with "other" in biological sex collumn
# data_with_ageDev<- remove_other(data_with_ageDev, "Biological.Sex")
# 
# #Seperate survey1
# survey1 <- seperate_survey1(data_with_ageDev, collumns_to_use)
```



### Create dataframe for DunedinPACE through rbind
```{r}

make_table_for_outcome <- function(input_df, outcome_column, input_young_old_boundary) {

output_df <- make_table_row_N_indivudals(outcome_column, young_old_boundary = input_young_old_boundary, input_df)

output_df <- rbind(output_df, make_table_row_continuous("Decimal.Chronological.Age", outcome_column, young_old_boundary = input_young_old_boundary, input_df))

output_df<-rbind(output_df, make_table_row_continuous("BMI", outcome_column, young_old_boundary = input_young_old_boundary, input_df))

output_df<-rbind(output_df, make_table_row_discrete("Stress.Level", outcome_column, young_old_boundary = input_young_old_boundary, input_df))

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Alcohol.per.week",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "chi"))

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Biological.Sex",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      use_only_categories = c("Male", "Female"))) # Specify categories if needed
                                      
output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Level.of.Education",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher_simulate",
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Tobacco.Use",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher_simulate",
                                      print_all_categories = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Hours.of.sleep.per.night",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher_simulate",
                                      print_all_categories = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Ethnicity",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher_simulate",
                                      print_all_categories = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Cancer.Diagnosis.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Cardiovascular.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed
output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Respiratory.Disease.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Endocrine.Disease.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Skin.Hair.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Gastrointestinal.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Genito.Urinary.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Musculoskeletal.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Neuropsychological.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Reproductive.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Immune.any",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Diabetes1",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Diabetes2",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Prediabetes",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "NAD",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "TA65",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "sulforaphane",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "DHEA_new",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Rapamycin_new",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "SASP_supressors",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Resveratrol_new",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed
output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "Exosomes",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "stem_cells",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "HRT",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE,
                                      categorical_var = "spermidine",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed


output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE,
                                      categorical_var = "fasting",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE,
                                      categorical_var = "semaglutide",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE, 
                                      categorical_var = "vitaminD",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

output_df<-rbind(output_df, fill_table_with_categorical(df = input_df, replace_small_counts = TRUE,
                                      categorical_var = "AKG",
                                      outcome_column = outcome_column,
                                      young_old_boundary = input_young_old_boundary,
                                      test_type = "fisher",
                                      print_all_categories = TRUE,
                                      display_only_true_vales = TRUE
                                      )) # Specify categories if needed

return(output_df)
}



```

### Create dataframe for DunedinPACE 
```{r}
df_Dunedin<-make_table_for_outcome(survey1, outcome_column = "DunedinPACE" , input_young_old_boundary=1) 

```
### Create dataframe for OMICmAge 
```{r}
df_OMICmAge<-make_table_for_outcome(survey1, outcome_column = "OMICmAgeAgeDev" , input_young_old_boundary=0) 

```
### Create dataframe for PC Grim Age 
```{r}
df_Grim<-make_table_for_outcome(survey1, outcome_column = "GrimAge.PCAgeDev" , input_young_old_boundary=0) 

```

### Create full table through cbind
```{r}
Table1<- cbind(df_Dunedin, df_Grim[, c("Old", "Young", "p.value")])
Table1<- cbind(Table1, df_OMICmAge[, c("Old", "Young", "p.value")])

#Rename collumns correctly
colnames(Table1) <- c("Variables", "Old_DunedinPACE", "Young_DunedinPACE", "P_value_DunedinPACE", "Old_GrimAge", "Young_GrimAge", "P_value_GrimAge", "Old_OMICmAge", "Young_OMICmAge", "P_value_OMICmAge")

```
### Save results as excel dokument

```{r}
#install package
if (!requireNamespace("writexl", quietly = TRUE)) {
  install.packages("writexl")
}

library(writexl)

write_xlsx(Table1, "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/Table1_survey1.xlsx")

# write_xlsx(df_Dunedin, "C:/Users/danwik/OneDrive - Karolinska Institutet/Documents/Project 2 - Vscode/Output/Table1_DunedinPACE_survey1.xlsx")

# library(dplyr)

# Females <- filter(survey1, Biological.Sex == "Female")

```


